### PR TITLE
Custom shipping logic

### PR DESCRIPTION
**Pull request by Swahjak**
Hi Marvin,

Just a pull request to be able to create a composer patch and test your new custom shipping logic.

### CODE REVIEW

**Comment by Marvin-Magmodules** [comment]
Hi @Swahjak great, let me know if this works out for you!

It's also available using composer: 
`composer require magmodules/magento2-channable dev-shipping-logic`

**Comment by Swahjak** [comment]
@Marvin-Magmodules it is, but my pipelines won't like that very much :wink: Thanks for the quick response(s) by the way.

**Comment by Swahjak** [comment]
@Marvin-Magmodules shouldn't https://github.com/magmodules/magento2-channable/pull/54/files#diff-c71ed59f358f6db859c5a1252150c744R689 be `$customCarrier = $method`

**Comment by Swahjak** [comment]
@Marvin-Magmodules It doesn't seem to work and I'm not sure why, do you perhaps have the json that is used for the test requests by channable? That way I would be able to reproduce the request on my local development environment.

**Comment by Marvin-Magmodules** [comment]
Hi @Swahjak, if you add /test/100 (where 100 is the Product ID) to the webhook url it will simulate an order import with Product ID 100. What are the values of the 'shipping_method' in 'sales_order'-table for orders shipped with Paazl?

**Comment by Swahjak** [comment]
@Marvin-Magmodules with #58 included this seems to work on develop. Will be testing this on staging an taking it to production in the upcoming week.

**Comment by Marvin-Magmodules** [comment]
Hi @Swahjak great, thanks for the PR! Please keep us in the loop, so we can merge this in an upcoming release.

**Comment by Swahjak** [comment]
@Marvin-Magmodules we've deployed this today. Ran into an issue which seems to be configuration related (on our side) https://github.com/magmodules/magento2-channable/issues/59. Currently resolving this. Should have some real results in the upcoming week.

**Comment by Marvin-Magmodules** [comment]
Great, thnx!

**Comment by Swahjak** [comment]
@Marvin-Magmodules So far so good.

**Pull request merged**
